{% set version = '0.3.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-languageserver
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/languageserver_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/languageserver/languageserver_{{ version }}.tar.gz
  sha256: 758260ea0506b284373262fb6f1fc1d89688e7b5f757569ef26462075462a2e9

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-r6
    - r-callr >=3.0.0
    - r-collections >=0.2.0
    - r-desc
    - r-jsonlite
    - r-lintr >=2.0.0
    - r-readr
    - r-repr
    - r-stringr
    - r-styler >=1.0.2
    - r-xml2
    - r-xmlparsedata
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-r6
    - r-callr >=3.0.0
    - r-collections >=0.2.0
    - r-desc
    - r-jsonlite
    - r-lintr >=2.0.0
    - r-readr
    - r-repr
    - r-stringr
    - r-styler >=1.0.2
    - r-xml2
    - r-xmlparsedata

test:
  commands:
    - $R -e "library('languageserver')"           # [not win]
    - "\"%R%\" -e \"library('languageserver')\""  # [win]

about:
  home: https://github.com/REditorSupport/languageserver
  license: MIT
  summary: An implementation of the Language Server Protocol for R. The Language Server protocol
    is used by an editor client to integrate features like auto completion. See <https://microsoft.github.io/language-server-protocol>
    for details.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Type: Package
# Package: languageserver
# Title: Language Server Protocol
# Version: 0.3.2
# Date: 2019-10-25
# Author: Randy Lai
# Maintainer: Randy Lai <randy.cs.lai@gmail.com>
# Description: An implementation of the Language Server Protocol for R. The Language Server protocol is used by an editor client to integrate features like auto completion. See <https://microsoft.github.io/language-server-protocol> for details.
# License: MIT + file LICENSE
# URL: https://github.com/REditorSupport/languageserver
# Depends: R (>= 3.4.0)
# Imports: callr (>= 3.0.0), collections (>= 0.2.0), desc, jsonlite, lintr (>= 2.0.0), R6, readr, repr, stringr, styler (>= 1.0.2), tools, utils, xml2, xmlparsedata
# Suggests: fs, knitr, magrittr, processx, purrr, testthat, withr
# ByteCompile: yes
# Encoding: UTF-8
# LazyData: true
# NeedsCompilation: yes
# RoxygenNote: 6.1.1
# Packaged: 2019-10-25 22:32:06 UTC; randy
# Repository: CRAN
# Date/Publication: 2019-10-26 04:40:02 UTC
